### ISSUE TITLE
Drop static site for SSR?

### ISSUE THREAD

**Issue by lucavallin** [lucavallin/first-issue#238]
The website is currently static. I've recently moved it to Vercel, so running it as a SSR app would work.
Making it dynamic would also remove some limitations in how we're building it/fetching data, creating links, passing data around, etc... so I think it's a good long-term investment.

Let me know your thoughts. Working on this issue also means removing the technical choices that were made because of the static nature of the site.

**Comment by dnafication** [comment]
I still think that the initial data fetching/processing has to be done in a batch process. That part cannot be done during the page rendering because of the size of the data and API request limits. We could introduce:
- A scheduled job separate from the deployment builds that would fetch and store the data in a database (SQL/NoSQL depends on the preferred choice)
- A new REST/GraphQL API that would fetch and serve the data from the database to the frontend

![image](https://github.com/lucavallin/first-issue/assets/6381587/5df2e47c-c411-4698-85cb-320eb543b695)
