### ISSUE TITLE
Reloading a language or topic page results in 404

### ISSUE THREAD

**Issue by lucavallin** [lucavallin/first-issue#25]
When on a language-specific or topic-specific page, if one reloads the page, then 404 is returned. This is because of how Next.js exports the static website. It would be nice to look into this and find a solution.

**Comment by thebarshablog** [comment]
Hey @lucavallin I tried loading several language-specific and topic-specific pages, as of present moment, it doesn't lead to a 404 error page but successful directs to the respective github repositories. Should this issue still be open?

**Comment by romeshkosme** [comment]
Hey @thebarshablog, it does lead to 404. Try [https://firstissue.dev/language/javascript/]

![first-issue-404](https://user-images.githubusercontent.com/40610011/210130467-24feb47c-18e8-4bf3-9347-c10341ee3263.png)

**Comment by thebarshablog** [comment]
In such a case, @romeshkosme, the issue should be renamed/specifics must be added. It's a happenstance under JavaScript whereas when I'm selecting based on other mentioned languages, its working just as fine. Please recheck again and confirm.

**Comment by romeshkosme** [comment]
@thebarshablog I rechecked the language-specific and topic-specific pages and they are responding 404 on page refresh.

**Comment by thebarshablog** [comment]
Right now, I agree that it does return an error. Would you like to work on this together @romeshkosme ?

**Comment by romeshkosme** [comment]
Hey @lucavallin  If nobody has picked it up, I would like to pick this one.

**Comment by lucavallin** [comment]
@romeshkosme Yep, feel free to work on this!

**Comment by JeniferConstantino** [comment]
Hello, is this bug still existing?

**Comment by lucavallin** [comment]
It is! There has been an attempt, see https://github.com/lucavallin/first-issue/pull/68. Unfortunately the fix there won't work for us.

**Comment by JeniferConstantino** [comment]
Hello, thank you for answering :). 

I would like to work on this issue but the problem is that I'm not being able to simulate the bug. I launched on development mode (npm run dev). When I launched, it took me to the website:

![image](https://user-images.githubusercontent.com/58510995/225599295-211fbcd0-cb25-4719-bae4-bfc4c5b037b1.png)

As said in the issue description, I went to a language-specific page and chose to browse by the language of "JavaScript", for example. Then I reload the page by clicking on F5 (or refreshing the link). By doing this I was expecting the error to show up, instead, everything happens as I think it should:

![image](https://user-images.githubusercontent.com/58510995/225599818-9a130e6d-727a-4dc6-9ace-04a7d463061d.png)

Am I doing something wrong?

**Comment by lucavallin** [comment]
Googling for `next js static site reload 404` brought me here: https://nextjs.org/docs/basic-features/data-fetching/get-static-props. Maybe a possible solution.

**Comment by tamiresviegas** [comment]
Hi @lucavallin I tried running the npm run export command to see the 404 error, so I had to run the npm run build command and I'm having problems, it's in an infinite loop trying to get the get. Have you got this error before?
<img width="548" alt="image" src="https://user-images.githubusercontent.com/8641078/226116831-be652e08-4dcf-4043-9a14-890cc69c7268.png">

**Comment by JeniferConstantino** [comment]
Thank you, I'm seeing if I can solve the bug :)

**Comment by tamiresviegas** [comment]
Hello goodnight. @lucavallin 

I realized that the error might be related to the token.
Have you tested the token to see if it's valid?

**Comment by tamiresviegas** [comment]
Hello goodnight.

I realized that the error might be related to the token.
Have you tested the token to see if it's valid?

Here's a curl test to see if the token is valid.

**Comment by JeniferConstantino** [comment]
Hello. 

I've been trying to make "npm run export", but before doing this I have to make "npm run build". When executing this command I get the following:

![image](https://user-images.githubusercontent.com/58510995/227739304-ec745560-e8ed-4cd4-bd1e-505dab9904b8.png)

And after waiting some time it retrieves me this:

![image](https://user-images.githubusercontent.com/58510995/227739468-367f13cb-911e-4887-b8f4-97c305992dba.png)

The code that is being executed is the following:

![image](https://user-images.githubusercontent.com/58510995/227739482-54e9b32f-5207-436c-a7af-c82f17f533ed.png)

With this being said, I conclude that the error occurs because I excited the number of requests to the API being used (60 requests as pointed out on the curl in the second image). I've read in here: https://docs.github.com/en/rest/overview/resources-in-the-rest-api?apiVersion=2022-11-28#rate-limiting that the number of requests can increase if I'm logged in GitHub. I've created a token, but now I'm not sure how can I log in to GitHub so that the API detects it.

Thank you in advance.

**Comment by lucavallin** [comment]
Hello! Ah yes, that's expected when running `npm run build` locally. We had a flag in place to avoid this but it seems it has been removed. Anyway, that happens because when you build the app, we get the data from GitHub to display it on the website. It's 1300 repositories and it goes through the API call quota quickly. What you can do for now is to remove the `prebuild` script from `package.json` so it is not called before a build runs. In this way, the app will use the `generated.json` data example that comes with the repo. Let me know if this works!

**Comment by JeniferConstantino** [comment]
Sorry for taking so long to answer. Ir worked :)

**Comment by MAdisurya** [comment]
Hey, not sure if anyone was still working on this, but I've put up a PR with a (hopefully) working solution to this issue :)
